### ISSUE TITLE
Percentages getting stripped from keyframe animations

### ISSUE THREAD

**Issue by g105b** [richthegeek/phpsass#120]
This CSS:

``` css
@-webkit-keyframes FadeAway {
    0% {
        opacity: 1;
    }
    100% {
        opacity: 0.1;
    }
}
```

gets converted to this:

``` css
@-webkit-keyframes FadeAway {
     {
    opacity: 1; }


     {
    opacity: 0.1; }
 }
```

Note that the percentages are removed completely, so the keyframe animation doesn't work.

However, using `from` and `to` works fine (although this is more limiting)
