### ISSUE TITLE
Nested + selectors prevent further parsing unless explicitly setup using &

### ISSUE THREAD

**Issue by Entoarox** [richthegeek/phpsass#122]
With the test case:

``` scss
p,ul {
    margin:0px;
    + p,+ ul {
        margin-top:0px;
    }
}
div {
    border:1px solid #000;
}
```

The ruby parser parses it as following:

``` css
p, ul {
  margin: 0px; }
  p + p, p + ul, ul + p, ul + ul {
    margin-top: 0px; }

div {
  border: 1px solid #000; }
```

But phpsass silently fails and returns the following:

``` css
p, ul {
  margin: 0px;
}
```

Any content after the `+p, +ul` fails to parse unless & is used to make the child selectors explicit (`&+p,&+ul`)
There are no errors thrown, parsing of the stylesheet simply ends at this point and the result so far is returned.
