### ISSUE TITLE
debug info don't works with Firesass

### ISSUE THREAD

**Issue by yukulele** [richthegeek/phpsass#132]
PhpSass debug infos are not the same as ruby generated sass ; line number have not the same format. and dont work with <a href="https://addons.mozilla.org/fr/firefox/addon/firesass-for-firebug/">FireSASS</a>

example:

generated by PhpSass

``` css
@media -sass-debug-info{filename{font-family:file\:\/\/C\:\\wamp\\www\/styles\/styles\.scss;}line{font-family:'4';}}
```

generated by SASS (Ruby) (work fine with fireSass

``` css
    @media -sass-debug-info{filename{font-family:file\:\/\/\/Users\/user\/www\/css\/style\.scss}line{font-family:\0000331}}
```
