### ISSUE TITLE
Nested selectors inside mixins not working correctly

### ISSUE THREAD

**Issue by thomasfrobieter** [richthegeek/phpsass#133]
Following code:

``` scss

@mixin horizontal-menu {
    width:auto;
    text-align:left;
    li{
      display:inline-block;
      border-width:0 1px 0 0;
      border-style:solid;
      border-color:#ccc;
      &.last{ border-right:0; }
      a{
        padding:1px 10px;
      }
    }
}

.region-header .menu{
    @include horizontal-menu;
}
```

The Result with phpsass is, that for example the - li - are printed out as single selector like this:

``` scss
li {
display: inline-block;
border-width: 0 1px 0 0;
border-style: solid;
border-color: #ccc;
}
```

Tested it here http://sassmeister.com/, result:

``` scss
.region-header .menu {
  width: auto;
  text-align: left;
}
.region-header .menu li {
  display: inline-block;
  border-width: 0 1px 0 0;
  border-style: solid;
  border-color: #cccccc;
}
.region-header .menu li.last {
  border-right: 0;
}
.region-header .menu li a {
  padding: 1px 10px;
}
```
