### ISSUE TITLE
CSS Function in mixin - grayscale

### ISSUE THREAD

**Issue by Maxence** [richthegeek/phpsass#134]
Hello,
I'm trying to create a mixin for grayscaling an html element.

In CSS way, it should be :

``` css
filter: grayscale(50%);
```

My mixin : 

``` scss
@mixin grayscale_element($value) {
    -webkit-filter: grayscale($value);
    -moz-filter: grayscale($value);
    filter: grayscale($value);
}
```

My error : 

```
Fatal error: Uncaught exception 'SassScriptFunctionException' with message 'SassNumber must be a SassColour
Source: -webkit-filter: grayscale($value)'
```

Problem is, in sass grayscale is already a function, and paramter should be a color.
Module: Sass::Script::Functions - Sass Documentation
http://sass-lang.com/documentation/Sass/Script/Functions.html#grayscale-instance_method

How can I use these filter in a mixin ?
