### ISSUE TITLE
variable overwriting

### ISSUE THREAD

**Issue by gamma613** [richthegeek/phpsass#144]
Here's a simplified version of some code that I believe is being incorrectly processed:

``` css
$x : #9f0;
$y : solid 1px scale-color($x, $lightness: -50%);


body {
    background:$x;
}
```

the result of which is

``` css
body {
    background:#4d8000;
}
```
