### ISSUE TITLE
CSS3 Pseudo-selector ":invalid"

### ISSUE THREAD

**Issue by SourceR85** [richthegeek/phpsass#146]
``` SCSS
form {
  input:invalid, textarea:invalid {
    background: #900;
  }
  :-moz-submit-invalid {
    box-shadow: none;
  }
  input:-moz-ui-invalid {
    background: #FEE;
  }
}
```

result:

``` CSS
form { input: invalid; textarea: invalid; input-background: #900; }
```

Mozilla-style is ignored
