### ISSUE TITLE
Can't @extend from included file

### ISSUE THREAD

**Issue by Raven24** [richthegeek/phpsass#28]
I have a `_mixins.scss` and I include that from my `style.scss`. In the `style.css` I want to extend a container class with a clearfix that is declared in the `_mixins.scss`.
But for some reason the generated CSS doesn't show the container being extended with the clearfix:

'_mixins.scss'

``` scss
/* Clearfix - h5bp.com/q */
.clearfix {
  *zoom: 1;
  &:before,
  &:after {
    display: table;
    content: "";
  }
  &:after {
    clear: both;
  }
}
```

'style.scss'

``` scss
@import "mixins";

#container {
  @extend .clearfix;
  overflow: hidden;

  & > div {
    float: left;
  }
}
```

which is compiled to:

``` css
/*
 * Clearfix - h5bp.com/q
 */
.clearfix {
  *zoom: 1; }
  .clearfix:before,
  .clearfix:after {
    display: table;
    content: ""; }
  .clearfix:after {
    clear: both; }

#container {
  overflow: hidden; }
  #container > div {
    float: left; }
```

P.S: Thanks so much for maintaining this project, I almost thought I had to put up with PHamlP from 2010, when all I need is a little Sass ...
