### ISSUE TITLE
font-size/line-height property doesn't compile right

### ISSUE THREAD

**Issue by CyntaxDotDev** [richthegeek/phpsass#29]
_Note that I've already posted this same response in the [following issue](https://github.com/richthegeek/phpsass/issues/15) but since this is another bug, I think it needs a seperate issue._

``` scss
p {
  $font-size: 12px;
  $line-height: 30px;
  font: #{$font-size}/#{$line-height};
}
```

This example is right off of the SASS reference page. Search for:
`"If you want to use variables along with a plain CSS /, you can use #{} to insert them."`
and you'll find it.

Where it says:
`is compiled to:`

``` scss
p {
  font: 12px/30px;
}
```

Which is obviously not the case, since trying it in the SASS command line and the /try of PHPSASS, I get a positive result in the command line and a negative result online.

What I get when running it in the SASS command line from my PC:

``` scss
p {
  $font-size: 12px;
  $line-height: 30px;
  font: #{$font-size}/#{$line-height};
}
```

Is compiled via `sass --watch sass:compiled` to:

``` css

p {
  font: 12px/30px; }
```

Online the editor itself returns:

``` css
p {
  font: 0px;
}
```

And the ruby console returns nothing.

Clearly a bug?
