### ISSUE TITLE
SassScriptLexer complaining about undefined index...

### ISSUE THREAD

**Issue by anandkkpr** [richthegeek/phpsass#49]
Hi! I'm not too sure where the problem is coming from but I'm getting a PHP Notice.

I've found a solution, essentially a check is needed to ensure that a usage of preg_match() actually returns matches. The new code simply has a condition that confirms the returned variable is an array and isn't empty.

As I said earlier, I'm really unsure about what might be causing the notice on my end and it's quite possible that it has something to do with the syntax in my SCSS file.

Error:
Notice: Undefined offset: 1 in SassScriptLexer->lex() (line 76 of C:\wamp\www\presence\1530chestnut.com\sites\all\libraries\phpsass\script\SassScriptLexer.php).

``` scss
// CODE FROM SCSS FILE
@mixin background-gradient($from, $to, $alpha: 1.0) {
  $rgbaTo:      rgba($to, $alpha);
  $rgbaFrom:    rgba($from, $alpha);
  $ieHexTo:     ie-hex-str($rgbaTo);
  $ieHexFrom:   ie-hex-str($rgbaFrom);

/* Old browsers */
  background: $from;
/* IE9 SVG, needs conditional override of 'filter' to 'none' */
  background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzFlNTc5OSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiM3ZGI5ZTgiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
/* Chrome10+,Safari5.1+ */
  background: -webkit-linear-gradient(top, $rgbaFrom 0%, $rgbaTo 100%);
/* Chrome,Safari4+ */
  background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, $rgbaFrom), color-stop(100%, $rgbaTo));
/* FF3.6+ */
  background: -moz-linear-gradient(top, $rgbaFrom 0%, $rgbaTo 100%);
/* IE10+ */
  background: -ms-linear-gradient(top, $rgbaFrom 0%, $rgbaTo 100%);
/* Opera 11.10+ */
  background: -o-linear-gradient(top, $rgbaFrom 0%, $rgbaTo 100%);
/* W3C */
  background: linear-gradient(to bottom, $rgbaFrom 0%, $rgbaTo 100%);
/* IE lte 8 */
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr = $ieHexFrom, endColorstr = $ieHexTo);
/* IE8 */
  ms-filter: progid:DXImageTransform.Microsoft.gradient(startColorstr = $ieHexFrom, endColorstr = $ieHexTo);
}
```

``` php
/*----------------------------------------------------------------------------------------
OLD CODE - @file SassScriptLexer.php
----------------------------------------------------------------------------------------*/
if (($match = $this->isWhitespace($string)) !== false) { // Line No. 67
  $tokens[] = null;
}
elseif (($match = SassScriptFunction::isa($string)) !== false) {
  preg_match(SassScriptFunction::MATCH_FUNC, $match, $matches);
  $args = array();
  foreach (SassScriptFunction::extractArgs($matches[SassScriptFunction::ARGS], false, $context) as $key => $expression) {
    $args[$key] = $this->parser->evaluate($expression, $context);
  }
  $tokens[] = new SassScriptFunction($matches[SassScriptFunction::NAME], $args);
}
```

Hope this helps!
