### ISSUE TITLE
@extend-Only Selectors support

### ISSUE THREAD

**Issue by dmnkhhn** [richthegeek/phpsass#56]
It would be nice to have support for @extend-Only Selectors as explained here: http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#placeholders

It has already been added here: https://github.com/richthegeek/phpsass/commit/2e3133a949e6459e5d01beb1810f4d3788e2b1e8

… but the PHPSASS online parser didn't compile as expected.

I tried it with this:

``` css
%media {
    overflow: hidden;
    &:first-child {
        float: left;
    }
    &:last-child {
        overflow: hidden;
    }
}

.status {
    @extend %media;
}
```
