### ISSUE TITLE
Using image data URLs emits notices

### ISSUE THREAD

**Issue by g105b** [richthegeek/phpsass#64]
This is not related to SASS-specific syntax, as it is standard CSS functionality.

The following, simple CSS code to produce a speckled background on the body:

``` css
body {
    background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAAH5FsI7AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3AsYEAgl1K7FqgAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAABZQSURBVHjafZzZduS2DkUhanb+/0OdjqsklYb7UN70FuLcXiurO3aVRIIYDg4ANl9fX9dxHMGfpmniuq5omqb+rO/7KMdx1F/yw67rou/7uK4rSinxer2i8MumaWKapoiIaNu2/t22bTRNE2UYhtj3PYZhiPM8Y9u2aJomtm2LruvqU7t936Pruti2Lc7zrL/kw/wpfd/Htm0xjmNERHRdF/u+1800TfN+NWtZ1zU+Pj5iWZboui7O86yb7Ps+utfr9X50KbEsS7RtWz/EZtZ1jXKeZwzDEHyBpVzXVf8upUSzrut1nmddz7qu0fd9ffK+72/xfX5+XhERwzBU0fAlnh4RUfIP+BDLGYbh/cGu6+L1ekXTNDGOY30Sp7OuawzDEN1xHHGeZ/R9X/9+vV717Esp0TRNdOd5xjzPERHxer1i3/fIf9Z1fa8RMfCUpmnqFziZZlmWyxuJiBjHMbZtqxuJiOh4Ghu5riv2fa9PR+BlGIb6gWVZqmJYe7Zti84CHoahHt04jnEcR/1w8/X1dbVtW08FNeMQ+NlxHNUSns9ntG1bf36e5484efowDFXWGCWSeb1e0fd9LMtSf9f3/W2vVcmWZbmQFA/OB3ieZ7XPdV2rINEClHEcx/cD2UbTNFUDIiL2fa8P2rbtbbPfJooI1nWtanae59sC0W5O5DiOeL1eVaN40XEc9e+u62JZlpjnuZrMMAxRcA7neUYppS6dLzRNU82c36Mz+C5scV3Xt95gPn3f11M7zzPGcayiOI6jPgiLiog4jiPato1932Oe52j++eefy76DL6Kcdrvo33Vd1eW1bRvP57Mqb0GgeDNOt+u6iIj3W7/VZ13Xm1h4KSLa9z2a5/NZ1QbPjBU0TVNXUkqJbdvuJ1pKlR0G26zrenH0OcqM4xjrulYLX9f1ZtCoEgfVtm10lg3bRGZ23siSGOPP2JsVtraua/17WZZYliXWda12uq5rfSFmhhtHVBERHW6GiIHqHMcR4zhWReZg9n2vD/IfXlz9F28gGqLQz+ezRh1+X0qJUkqM41gDNHpbjuOIaZriPM+b8k7TVIMzsuQQOHH+7vu+OpXC9l6vV13ZcRzxeDxuJ27PizXhVBHDdV1v58DBsHxkx5sJi9g0Zso2eWnbttH8+fPncthBHnZj13XdIgy279/XeIbJsTq2xSr4f8KtY4p9IYfVIRtWwZeMc8ZxjNfrVQOpkRWBFORSUFaHOHTSAXYYhh9I9i1fHAJIbNu2KI4fvOm6rqo2nCa2imrheTi0Klecg4XPL4l2EVFPGPjS9321aVtSh2Ly9lLKbbVYDsGKMIuTGMexqs91Xe9DwcxQA1wVNouLwr3xexZC1CylvAGqMRzwkUOIiHg+nzfwZQjnXUTEG3ba/aPxyGkcxxt+YeuIhs/xnA65Yehsm9UhCk6e1XPqKDSfKcQEGz/mZ3wDoOJFqBpOoSLEP3/+XHaqnB4Olm2xCg7I6AwPDqCapqkeEmrGQSJ7ROXfEehwA/u+/0AbXoA/naapGgQAwckGiA7z3/e9ahJgYhiGKKVU0fM5OzLchO0F6z/P8600DuvsEuvFibFbIjMvInDgkksp1Rkuy1KRNnYEvOLIeS8CcFCPiHsSYISEVBE/L+a40Rf8F1LHC2NuhhjOGa/rqqHUSYe91DiOUQwv8BpGXsuyxDAM1ezYrS3DIdS+YJ7nKnUkN89z7Pt+8wX2wUixlML3Sv0AC5imqeJxHwMbYJG2QI7cuRASxq/wM4TAabBJpGy3UfglO0LMOHfjWcMjlJoF8QJ0CUjAy6qn/NZb9Juw5kBDLnGe5xsYOkc3vsX18EVHMGJm27Y3+gO3jf5yAugvkjEs5tSQqKmADreCFM/zrDvnWJEyVomE0VHjRNwJi7WeEcv5r23besT4TQfJbdveRwyKwLJI28z54FCJDg7foGWODncyDEM8n8+b2zA8RxjjOFZ95p0IoBInWCIJK8bAfxwF+Ow8z7oJgAg+ctu22LYt1nV9K/q3xZsbYgNID3Xhs5xEh9TQLcITDphjQS9++wM0c4aOkTmvY5EYCmjhOI6qj/aN/+J/WAiSMJ62Mdmg0CGslcWR6WdWEiNCKCxonufqugwsut9iINZ3nmfF4vgwHCix2pEBCfEcFsDvkSYWbV2GTOHnNW9AefmFCROiCxCUkMQL+YzJNY7HqgOK5MVICnXiiM1ecGJdZWG/rdPJHB9ioeiJPf5xHBV+sVFDJiRq6MZGCKEYDWuwIy/8AMtDFzlCJMVG7HxJdtgUDwa4I0V0lmg1TVNN70xXY0iEzW3bovn7778vpGFDMG1YTf5bX8l3zHIaUiEl66RJFueb6CpSxblXOp0fOpFlZ/wbJ2ragp8RYZAsR2M6zlCeDZmqNXoxfX8cxzuSuCJgl+CAzkawaCMQLJwTeL1e9WgJhQARjj9TBTwPxw0SqnwresLR4g+B5M7jzBTjx3DA8NQ2KkM6x+BaePkOldM01e/jHYol5hf6Dw/Gv7EAXu5SBtaMI5+m6WZMSNGlDyAaYISItCzLm3q077ORIFX/yc7YR4YuY42mgrwQjIjcBdUguSKSDMPwLkJZ9AYKLMJA0qEIouHj4+P2PUMsBwFDMDMe6DTIxy6qczZlZtwx1U4b5ILkuq6raITNuGTDSbBJwzQsnYhEzu3PFyurE+u6A+E3wp4Tb/SMiEKS5SqIjQuI5gSJagDqcStymJByboKig6qNslEH+7rKwX1v+Pl83mpZLvvh80z7AvvR0frsXFyC3uBI7evMgdaaogzKyHyappimKeZ5vvEtWLDRMwJhE1RBIyI6J8tmzu1KzD6YX8UluYjnEGi1MIXi45+mqQqA+ozZ0cJL2In5MPsqI5ac+PAiIoEtmSODeP/NutE9g2NUoVnX9eKhj8cjPj4+6gPw6izA5WI79Myp2NeZfSRSsaAMFgz9CKsF5cfHrev6L/CJPmS6YhzH2/+zIdwJbsdBAM/A90yhoufE7uM4fsijYRgqKrFO5ShiSbmCATzCyHIu49o8J4Cjdnh0KtE0TRT8jdnjmlGpBACqcTG27lIlfC+ESMTPTd3ZxWD9RBiHyXKe581nwefh2Y2UbTTgQIhLQIRxoiumxNrs9Nkk4Q4vUp24W0vMEbKYXHlxK4K/i3q8Xq8bBuSlr9eruhGfgtGUy0RAveJIwFH6wXwBpacoQ8RwOKtNK9+SJ3wRz4kUrq/+VssyQ9Y5pzV6sTfnpeZWLFkSH9dsYBqshxgEAgE02GVlV9U8n8/LgR//5RTAUIxowMtz74gzPCTDKXGsHx8fVdcRAkyE6eTrut5pZ06UjEBMELlU5nDIQvAG2S25bscRm9VCL1msue5mWZbLRWiLG/0AjLJQgKf7HZw6AhAyCZBjc+3K+A6rziprMp+L1hw1lumijS0SS3aSDivm+qppY5NL6DWLyw1WtV/KESPHSQyIEOaCG3QIvo8I5GjiOGwDw5hc0CO7A5nX5gVjPD6Ef0LsOcdw1QjFZkOoBEZFZRDUzQIApGaynCVyUoUE2f7MLsNlLWM8kIlzFnzYvu+1p4Z4TdXW/KCdshl/R56CtDgmmtjc0OO4apWwv3MUMrox5+IT4POkAeg1/pfaSkHkFm32X/DXHD8bMMds3jnX25AKOgp49WYMhB2/CyHJrVEWs7+MRRIBTNfxe0q67vmw6piKcz8XESjXj5tlWS52R0KDo8xspyMLABc1wAKtCmYgMAw8A5vhVNy/4/J78+fPnyvHXMMd0xgGqig4LgkLdWrqzzks2mrdSgJsYyMVD2IELhfkHj5gO1a4LEtVbKMTcys824Vu3Bk4EqEQVYD9lOKKYZKJo1w/do+Lu6CwZJh7sB54jg3SKgBS6vu+JmgsdNu2aki1Q8oLc9JDxLBuOocGvoMf/RxeYESUK+5YPymGuWoXwLucDOFaHKOxMgCFy7MkS1ZsNtK2bTwejyptM6psGAN1v4QBcGdoxHGBoK2DRtcuyCABjsYSwyOYBMCd8W8s2DDvJpzcVJljo8MY2ZddjcOZK+p+CX4WiWEMXhybZsOcQuHYOGaCupPqrE92FfAqRBjITJAKhLi71cxHeiM2lpoXu+WIF1ovgVve3W8NkTna4Drch2eq2H06le79rr/ws77v34UcW5/TRV7sxkrzJrVUoDTV+uROLwNfLNr40YGBZ1c8mHMCROzj+K1PPtdUnEihl4S5PG2Qe9AhQBFGJT4ZfkAqbs52vcJFP4K8+xxMoLveUhuPv43PYdAbot2VZ7n5zCU0gxlivUtn8zzfTun5fMZff/0VX19fN1LK+AA7sMCMiymjPJ/Pmm2CfUvWZwsCcEIMBymZ7TC/ZKzgsOsAQagmGto+qKDh/1m4tZCwjtq7QcDgHM9mCGDTQP0RpiuCBlbsJQ8x1LyPjXByqCtYxQ9GW8AZGYzhxp2GoaW5g92CvjHSKhvxjOfzWesMfqc7fHD95uBIAdF218mcSJM447mdz9KI42INhzVN009fVB54Mgg0gjVDnml/t87lKTB3UpPgeBAETTFyoCfGyZGLf2A3rxEKzpWkiKjN6+u63gqSOHI3GP9WTWUdpk/qKJT7rYxq8P6YbaYwALDwhWhYJuHdHgro8NSCTR5nTRiFefUoj1NhtNA0C6AmsxVu+AWU4wLmeb5pn62E+MBaXLIu7pXNM28ev3OnJ5qX69PuXjEvRICAFTaJatzqSQRM0NVagI+ramifR+9MgBinOCrntMnsIPmfe0GcojmgNp+fn5fbwZzlZnbGDaB+IFpxHEfM83yrYVpwLpxharmlG+GO4xiPx+NfjdOuXzkXtHCAGMZIaGZu7XVtAfZIKDS6rovH41HpL/yhfPqPCSI8wxcLFg1BGGgFplNrp9+a6SEEIp7hAYM2mH+uZptBIBc1d4IrcS+V81uiM//OY4Q3ZkDuBD/N4c7z/MOkilapSBr8BCyxinqUy1ACv/Xx8VFZLTTZXW6mhQkYnq+g49KMFwfm9haTmZitcaLNzWU3tD/z7p4lwE1Zk31YdA6gGLc2MYNTt/E5XcjOF5MiT0IAhhD4RczQuT+JH6SFS3zuZzMvhYvgva455mKqR5x+A/+/FV8RtFt28H3sEUXwu4sb4TgBnOhvOb6zFNcxHQzcicii+J5HWyx4s4y4CwIGh4i5GSEAadwBnt+Db3bG7cBiwhCs6UP39CBrqs2JnqdwYDBMuA3nfz/YWmOTcn87uA8MR/HZE4ge48kH6QNFa1yGN+PkdhJbDPyezdFQiX8/Ho/wIG4eA3F7NAd5nud7etd9+giSiGUuBl/nIXEW5T4ZTs1FIOCNfY6LjgQaN0R6ZMlTGfybwOLueSwCC0IB/DOClpEAz87Cc1nZZG5NcXNLqstpnhPouq6CTfsyAKwrYtlEMuzJJC3vI7PIC7cP8mA4gsPsWQs/r+3X3yCalgz7W9dOGfU2r+q82TCqdvp7LJ5IBPAFPvAlE2s4WvJDtMtzXpk1QZDgKWACz7ag3XVt7EVS71TSDQVuG/JsmtmcPCfr5hcPAJgRdUuw3UxxlmEyMKdYNKhywpikQaXb4+wzXcswQ5IxpxsJnW+TgfjmEiK5N0O6aYsAkhkH8pzsh+1ebmO+AvgoBkGsWJU9gcCHMj/msj2sjEsNxlcewzDrn5sYIRE8OA4viVDwwVgG7oU8/TiOWmdhjTh/t0zDVaKVzmQczCBg0XrXJz0wUcB+Bpemj12HzqVhR+zcIGfNcAM6kIHD8h0CTqOcdv1WwnMbtlthnU2Y5/9tgNIslDtpwJwmPdBw3Eyl7OjcR1i+oyW/zK2w7vqz9jkZd6XXhIU79MGShlGGJ7nOn28CMqHqZj60LV+Rg1CI+r7Cg0hrFtypZW6AuK7rTeljKpgDao5w3CTo2R4WYHCdx7NNxDqRz4v0bAaBKF/IZATgrMO/dw0tHzSkrJsgje3y8zwQj8m6wbxpmvdtQh5z9Mk+n8/qQzxjbj7MXbp5RsT9Xf68e2MslHr5zfe/gSdcPeOMJjt3R3gQAdplgWfC1NygmyhzuueUEwRRrx+xRrlu4CKnUx77p3meqw911zEYKje1e1INvGbsaQrdGYzLy754yZprqt6kgkdLM/fomZ48ye4+T/vZ20UxRvy8LDcB+AYpmA9fc2PujBehmWZWnGsairAB6jAWvrlC976bbDXWBGADZYAezlSguKz9eeLUONH+z7d2lFLezaouKv3m2DGj3Bf1/4ab8qhY5c9ST7MJ2hyMiMruMXVEdwDh82ZNPLJhVtndlJmIzev6r9b5G5lgLJQX7SYegg3a6EX4zhRfYZCbgtCc3E08z3M8Ho9bKcHW4GZJV+ScZaCdYFSEaTeS/bTfxX2EHlnCbbmN2g0kxQP6Znpxpq72504pn57n8V3z8GdNfJLZ+G4T+0NM2Jdb+P4tcm77Ml8bZaKVvfiuALunPNjLIbnUirANt/Z9fw8GOY81QHYhiQX7Gkz3prv65gvebNrMSWRfk6fhzYa4KufuQnfP+qIkEwjOGCgZZMRhoTgv91gt33PrLz61y5eosTC3vfnL7pP3PJtBrmsfpFt20i6jguox39+Eavbb/ftuAiNtyxOCzos5YDPw+He01zeuuHbsFhJ3OJVchTeN44K4h+0xF5c2PQCYL+zE6dotmP8zEM4jH0TW3NVuwOw0EVdiQoM9oP1uTHKfrbslXD7IaauL+iVf2uZOuNydiTaaXsdPUJTKhCrBgs27ec1NbmaJXaN1Wz/vNOzK0+kGyBzSf9VyTFr4phCTqgQx3AM95jVv//z8vDxeat/lZjpM1gs2bszXOJic8Airbiu6LcqdDGZC7Kv8Pvs6fGW+QMZ3iWa4Qq07p6wuyrNW3zZmNmYYhp8mVbPSAE/nvky3ZAGjHV6EE/J8j0YmLj3l4pQs9+L4QH09nyf/rTmAepdp0UJXBY0V6cLKV6t5UMtE8bZt9z7p3FDkYs3Hx8etfc3TDKamfqO2gAw5KkM1+dJjtyDnqGd2GJ/mu2vctuH3c1iUEqjlWOvdwWXFwAejJADoWjv3dVcugLv3j+ZCt7DmoQaXR8FeCAgBu2PKc6nuOrC2udvL1DzBxXNY5gytuc5SXK+h3MrB+R6V3A/j+W1fb9L3/c9AEJoEirdfgh3xyeQbWk045CalfGF3Low7VfMojC/6c1NRvizGt9+Yaf6vSRffd5tvWPI9L3nYyXWSevFbRuF+MaA114VzN4AvIDQrkjk3BxoP6HnCyljS15Z59MKBwQwM7+dv31yWmz5RCt+y58htpGAMbJRxuxnbgyn2VZ51A7DmcR427otJ3R9twhTVtxnmvkObN5txRTDfwIdVELgMtvFfxqxmup12msX2XWMeJcnMULMsy5XpeLfW0jzkbMTFaF9H7N/5+i0PVHPKvo4wQ4ychfhqENrn3MPNs0n78r1hZl/sO3+7QxeMaMbFiMGXBE7T9KOBfNH3iAGO3eTti/V8rYgrbIYavt02N1B6NNq3ZDods6YZl3n0Ktc33LTuSRZPqJqg9Xow3XwXLpHe85C3S8V9427WmN/oKPdSE0zcn2yYwyEQpADlhhoucNuNWFvdmeW7i32FqdkhD5+S0VBtMwOeC/p5Bhml8MVh/PkfV8+wJaYmaTQAAAAASUVORK5CYII=);
}
```

When parsed using phpsass, it emits the following notices:

```
Notice: Undefined offset: 2 in script/SassScriptLexer.php on line 73
```

```
Notice: Undefined offset: 1 in script/SassScriptLexer.php on line 76
```
