### ISSUE TITLE
Bug using attribute selector

### ISSUE THREAD

**Issue by g105b** [richthegeek/phpsass#72]
When selecting something with a particular attribute, the selector behaves as if it was selecting using the `&` prefix.

``` scss
.container {
    [type='radio'] {
         // Should select all radio inputs within container...
        background: red;
    }
}
```

``` css
/* where actually it is selecting all containers with a type of radio :S */
.container[type='radio'] {
        background: red; }
```

I can get around this bug in my particular application by using the `>` selector to ensure the `[type='radio']` sub-selection is made on a child of `.container`.
