### ISSUE TITLE
imposible to use slash in style

### ISSUE THREAD

**Issue by yukulele** [richthegeek/phpsass#83]
php sass aways interprete `/` char as divide operator

``` css
p {
  font: 12px / 10px;
}
```

[SASS reference workaround](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#interpolation_) don't seem to work :

``` scss
p {
  $font-size: 12px;
  $line-height: 30px;
  font: #{$font-size}/#{$line-height};
}
```
