### ISSUE TITLE
@each malfunctions

### ISSUE THREAD

**Issue by wellagain** [richthegeek/phpsass#87]
In **Ruby**, this code: 

``` scss
$default-prefixes: webkit moz ms o;
@mixin prefixize($property, $value, $prefixes: $default-prefixes) {
    @each $prefix in $prefixes {
        -#{$prefix}-#{$property}: #{$value};
    }
    #{$property}: #{$value};
}
li {
    @include prefixize(box-sizing, border-box, moz webkit)
}
a {
 @include prefixize(box-sizing, border-box)
}
```

compiles into:

``` css
li {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box; 
}
a {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  -ms-box-sizing: border-box;
  -o-box-sizing: border-box;
  box-sizing: border-box; 
}
```

In **phpsass**, this very same code seems to miss the @each part and compiles into:

``` css
li {
  -moz webkit-box-sizing: border-box;
  box-sizing: border-box;
}
a {
  -webkit moz ms o-box-sizing: border-box;
  box-sizing: border-box;
}
```
