### ISSUE TITLE
Nested rules in media queries don't work

### ISSUE THREAD

**Issue by dsutoyo** [richthegeek/phpsass#9]
For example, this works:

``` css
@media only screen and (max-width: 480px) {
    .excerpt .attachment-thumb {
        display: block;
    }
}
```

but this doesn't:

``` css
@media only screen and (max-width: 480px) {
    .excerpt {
        .attachment-thumb {
            display: block;
        }
    }
}
```
